FROM node:18-alpine

WORKDIR /app

COPY package.json .
COPY package-lock.json .
COPY tsconfig.json .
COPY vite.config.ts .
COPY postcss.config.js .
COPY tailwind.config.js .

RUN npm ci

ENV NODE_ENV=development

EXPOSE 3000

CMD ["npm", "run", "dev", "--", "--host"]