spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    driver-class-name: org.h2.Driver

  redis:
    enabled: false

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  api-docs:
    enabled: true
    path: /v3/api-docs
  show-actuator: true
  packages-to-scan: org.noisevisionproductions.portfolio

application:
  security:
    jwt:
      secret-key: testsecretkey123456789012345678901234567890

server:
  port: 9090
  error:
    include-message: always
    include-binding-errors: always