export enum Authority {
    CREATE_PROJECTS = 'CREATE_PROJECTS',
    EDIT_PROJECTS = 'EDIT_PROJECTS',
    DELETE_PROJECTS = 'DELETE_PROJECTS',
    SEND_MESSAGES = 'SEND_MESSAGES',
    ACCESS_KAFKA_DASHBOARD = 'ACCESS_KAFKA_DASHBOARD'
}